### ISSUE TITLE
Unwrapping Applicability for Complex 3D Models

### ISSUE THREAD

**Issue by jxxtin** [3dlg-hcvc/omages#1]
Hi, thanks for sharing your amazing work @QhelDIV 

I have a question regarding the UV unwrapping for 3D models. 

Is UV unwrapping generally applicable to 3D models that consist of multiple assembled meshes or objects with numerous geometric modifications like holes?

**Comment by QhelDIV** [comment]
We assume the 3D model is already unwrapped. Typically, to unwrap the complex model, 3D artists first cut it to simpler patches, then perform UV unwrapping on those patches indivisually, which is usually done by surface parameterization algorithms. 
So yes, UV unwrapping is general applicable to all kinds of 3D models.
