### ISSUE TITLE
Separate Training of null2geo and geo2mat

### ISSUE THREAD

**Issue by jxxtin** [3dlg-hcvc/omages#2]
Thank you for your kind response @QhelDIV.

I have one more question regarding some training process.

Why is it necessary to train null2geo and geo2mat separately?

Wouldn't it be possible to include the geometry/PBR map together in the diffusion process?

**Comment by QhelDIV** [comment]
Yes, you can directly train the 12 channels together. 
However, the precision requirement for geometry and material is very differnt.
int8 level presision is enough for materials, however, good geometry requires at leat int16 precision.
Also, in our experience, it is easiler to obtain better geometry in this sequential order.
