### ISSUE TITLE
Blender error

### ISSUE THREAD

**Issue by linziqu** [3dlg-hcvc/omages#7]
Thanks for your work!

I came cross this error when using this function objamage_decoderv2 and then the code is over without any results.

WARN (bke.customdata): source/blender/blenkernel/intern/customdata.cc:4544 CustomData_layer_ensure_data_exists: CustomDataLayer->data is NULL for type 46.

That's the issue with my blender?

**Comment by QhelDIV** [comment]
Probably yes. Try to reinstall the bpy package.
